USE company_db;

CREATE TABLE employee(
emp_id INT PRIMARY KEY,
emp_name VARCHAR(100) NOT NULL,
salary FLOAT,
dept VARCHAR(50) NOT NULL,
hire_date timestamp
);


ALTER TABLE employee
ADD email VARCHAR(50) UNIQUE;

ALTER TABLE employee
DROP dept;

ALTER TABLE employee
MODIFY salary DECIMAL(10,1);

RENAME TABLE employee TO company_employee;

TRUNCATE TABLE company_employee;

DROP TABLE company_employee;

-- CREATE IS USED TO CREATE TABLE IN DATABASE

-- ALTER IS USED TO MODIFICATION IN TABLE LIKE ADD COLUMN AND REMOVE COLUMN

-- RENAME IS USED TO RENAME TABLE NAME

-- TRUNCATE IS USED TO REMOVE ENTIRE DATA FROM TABLE 

-- DROP TABLE IS USED TO REMOVE ENTIR TABLE 